package com.vivek.spring.cloudfunction.aws.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "input_data")
public class Data {
    private String id;
    private String input;

    public Data(String input, String output) {
        this.input = input;
        this.output = output;
    }

    public Data(){

    }


    private String output;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }

    @DynamoDBAttribute
    public String getOutput() {
        return output;
    }

    public void setOutput(String output) {
        this.output = output;
    }


}
